const WEAPONS = [
    "A Wrench",
    "A Candlestick",
    "A Knife",
    "A Pipe",
    "A Revolver",
    "A Rope",
    "An Anvil",
    "Poison",
    "A Bear Trap",
    "A Ninja Star",
    "A Sword",
    "An Axe",
    "Motor Oil",
    "A Mouse Trap",
    "A Dumbbell",
    "A Trophy",
    "A Potted Plant",
    "A Prized Pumpkin",
    "An LED TV",
    "A Gavel",
    "A Cane-sword",
    "A Guitar",
    "A Pillow",
    "A Banana Peel",
    "A Deadly Fungus",
    "A Venomous Snake",
    "A Pen",
    "A Harpoon",
    "A Thorn from a Rose",
    "A Bow & Arrow",
    "A Crucifix",
    "A Javelin",
    "A Gauntlet",
    "Brass Knuckles",
    "A Sickle",
    "A Hammer",
    "A Crowbar",
    "A Mace",
    "A Set of Nun-chucks",
    "A Rock",
    "Tap-Dancing Shoes",
    "A Throwing Dart",
    "A Boomerang",
    "A Crossbow",
    "A Cat o' Nine Tails",
    "A Musket",
];

module.exports = {
    WEAPONS
}
