const STORY_PREFIXES = [
    "Sherlock Holmes and the Case of the {A1} {N1}",
    "Star Wars: Episode VI - {N1} of the Jedi",
    "Harry Potter and the Sorcerer's {N1}",
    "Percy Jackson and the {N1} Thief",
    "Mission: Impossible - {A1} {N1}",
    "Call of Duty: {A1} Warfare",
    "James Bond: From Russia with {N1}",
    "James Bond: The Man with the {A1} Gun",
    "Indiana Jones and the {N1} of Doom",
    "Indiana Jones and the Kingdom of the {A1} {N1}",
    "Avengers: {A1} {N1}",
    "The Girl With The {A1} Tattoo",
    "A Song of {N1} and {N2}",
    "The Hitchhiker's Guide to the {N1}",
    "To Kill a {N1}",
    "The {A1} Gatsby",
    "The {A1} Heart",
    "War and {N1}",
    "{N1} and Peace",
    "{A1} Fiction",
    "Pan's {N1}",
    "{A1} Encounters of the {A2} Kind",
    "The Lord of the Rings: The Return of the {N1}",
    "The Lord of the Rings: The Fellowship of the {N1}",
    "The Beauty and the {N1}",
    "Live Free or Die {A1}",
    "12 {A1} Men",
    "{N1}busters",
    "{A1} Frankenstein",
    "Almost {A1}",
    "Monty Python and the {A1} {N1}",
    "Eternal Sunshine of the {A1} Mind",
    "Butch Cassidy and the {A1} Kid",
    "The {A1} Lebowski",
    "Some Like It {A1}",
    "A Clockwork {N1}",
    "American {N1}",
    "The {N1} Bride",
    "The {N1} of Music",
    "It's a {A1} Life",
    "Gone With the {N1}",
    "Indiana Jones: Raiders of the Lost {N1}",
    "Night of the ${A1} Dead",
    "{A1} Miss Sunshine",
    "The Secret {N1} of Walter Mitty",
    "It's Always {A1} in Philadelphia",
    "{A1}-Cop",
    "The {N1} King",
    "The Scorpion {N1}",
    "Lara Croft: {N1} Raider",
    "The {N1} of Oz",
    "The Lion, the Witch, and the {N1}",
    "{N1} of the Flies",
    "The {N1} of Dr. Caligari",
    "{N1}-Man: Into the {N1}-Verse",
    "{A1} Max: Fury Road",
    "Snow White and the {A1} Dwarfs",
    "E.T. The {A1}-Terrestrial",
    "Call Me by Your {N1}",
    "A {N1} Named Desire",
    "The {A1} Life of Zack and Cody",
];

module.exports = {
    STORY_PREFIXES
}