const STORY_FOR_SYNONYMS = [
    "Some Like It {Hot}",
    "James Bond: The Man with the {Golden} Gun",
    "James Bond: The Man with the Golden {Gun}",
    "Indiana Jones and the {Temple} of Doom",
    "Indiana Jones and the Temple of {Doom}",
    "The {Great} Gatsby",
    "War and {Peace}",
    "{War} and Peace",
    "Pan's {Labyrinth}",
    "{Close} Encounters of the Third Kind",
    "The Lord of the Rings: The Return of the {King}",
    "The Lord of the Rings: The {Fellowship} of the Ring",
    "The Beauty and the {Beast}",
    "Live Free or Die {Hard}",
    "Live Free or {Die} Hard",
    "Live {Free} or Die Hard",
    "{Live} Free or Die Hard",
    "12 {Angry} Men",
    "{Young} Frankenstein",
    "Almost {Famous}",
    "Monty Python and the {Holy} Grail",
    "Monty Python and the Holy {Grail}",
    "The {Big} Lebowski",
    "The {Sound} of Music",
    "It's a {Wonderful} Life",
    "Gone With the {Wind}",
    "Night of the {Living} Dead",
    "{Night} of the Living Dead",
    "{Little} Miss Sunshine",
    "It's Always {Sunny} in Philadelphia",
    "Lara Croft: {Tomb} Raider",
    "The {Wizard} of Oz",
    "The Lion, the Witch, and the {Wardrobe}",
    "The Lion, the {Witch}, and the Wardrobe",
    "The {Cabinet} of Dr. Caligari",
    "{Mad} Max: Fury Road",
    "Call Me by Your {Name}",
    "A Streetcar Named {Desire}",
    "The {Magic} School Bus",
    "The Legend of Zelda: {Breath} of the Wild",
    "The Legend of Zelda: {Wind}waker",
    "The Legend of Zelda: A Link to the {Past}",
    "The Legend of Zelda: Ocarina of {Time}",
    "The Legend of Zelda: Majora's {Mask}",
    "{Super} Mario Brothers",
    "{Dark} Souls",
    "The Elder Scrolls V: {Sky}rim",
    "The {Elder} Scrolls V: Skyrim",
    "Red {Dead} Redemption",
    "Red Dead {Redemption}",
    "{Resident} Evil",
    "Resident {Evil}",
    "{Over}watch",
    "{Final} Fantasy VII",
    "Final {Fantasy} VII",
    "Guitar {Hero}",
    "{Silent} Hill",
    "Silent {Hill}",
    "The {Legend} of Zelda",
    "Castlevania: {Symphony} of the Night",
    "Castlevania: Symphony of the {Night}",
    "Super Smash Bros: {Melee}",
    "Super {Smash} Bros: Melee",
    "{League} of Legends",
    "The {Twilight} Zone",
    "The Twilight {Zone}",
    "Breaking {Bad}",
    "I {Love} Lucy",
    "{Arrested} Development",
    "{Parks} and Recreation",
    "Buffy the Vampire {Slayer}",
    "Buffy the {Vampire} Slayer",
    "Star Trek: The Next {Generation}",
    "Mister Rogers' {Neighborhood}",
    "{House} of Cards",
];

const STORY_PREFIXES = [
    // TITLES
    "Sherlock Holmes and the Case of the {A1} {N1}",
    "Star Wars: Episode VI - {N1} of the Jedi",
    "Harry Potter and the Sorcerer's {N1}",
    "Percy Jackson and the {N1} Thief",
    "Mission: Impossible - {A1} {N1}",
    "Call of Duty: {A1} Warfare",
    "James Bond: From Russia with {N1}",
    "James Bond: The Man with the {A1} Gun",
    "James Bond: The Man with the Golden {N1}",
    "Indiana Jones and the {N1} of Doom",
    "Indiana Jones and the Kingdom of the {A1} {N1}",
    "Avengers: {A1} {N1}",
    "The Girl With The {A1} Tattoo",
    "A Song of {N1} and {N2}",
    "The Hitchhiker's Guide to the {N1}",
    "To Kill a {N1}",
    "The {A1} Gatsby",
    "The {A1} Heart",
    "War and {N1}",
    "{N1} and Peace",
    "{A1} Fiction",
    "Pan's {N1}",
    "{A1} Encounters of the {A2} Kind",
    "The Lord of the Rings: The Return of the {N1}",
    "The Lord of the Rings: The Fellowship of the {N1}",
    "The Beauty and the {N1}",
    "Live Free or Die {A1}",
    "12 {A1} Men",
    "{N1}busters",
    "{A1} Frankenstein",
    "Almost {A1}",
    "Monty Python and the {A1} {N1}",
    "Eternal Sunshine of the {A1} Mind",
    "Butch Cassidy and the {A1} Kid",
    "The {A1} Lebowski",
    "Some Like It {A1}",
    "A Clockwork {N1}",
    "American {N1}",
    "The {N1} Bride",
    "The {N1} of Music",
    "It's a {A1} Life",
    "Gone With the {N1}",
    "Indiana Jones: Raiders of the Lost {N1}",
    "Night of the {A1} Dead",
    "{A1} Miss Sunshine",
    "The Secret {N1} of Walter Mitty",
    "It's Always {A1} in Philadelphia",
    "{A1}-Cop",
    "The {N1} King",
    "The Scorpion {N1}",
    "Lara Croft: {N1} Raider",
    "The {N1} of Oz",
    "The Lion, the Witch, and the {N1}",
    "{N1} of the Flies",
    "The {N1} of Dr. Caligari",
    "{N1}-Man: Into the {N1}-Verse",
    "{A1} Max: Fury Road",
    "Snow White and the {A1} Dwarfs",
    "E.T. The {A1}-Terrestrial",
    "Call Me by Your {N1}",
    "A {N1} Named Desire",
    "The {A1} Life of Zack and Cody",
    "The {A1} School Bus",
    "Grant Theft {N1}",
    "The Legend of Zelda: {N1} of the Wild",
    "The Legend of Zelda: {N1}waker",
    "The Legend of Zelda: A Link to the {N1}",
    "The Legend of Zelda: Ocarina of {N1}",
    "The Legend of Zelda: Majora's {N1}",
    "Super Mario {N1}",
    "{A1} Souls",
    // QUOTES
    `"Frankly, my dear, I don't give a {N1}." - Gone With The Wind (1940)`,
    `"You're gonna need a bigger {N1}." - Jaws (1975)`,
    `"A martini. Shaken, not {A1}." - Goldfinger (1964)`,
    `"I see {A1} people." - The Sixth Sense (1999)`,
    `"Well, nobody's {A1}." - Some Like It Hot (1959)`,
    `"It's {A1}! It's {A1}!" - Frankenstein (1931)`,
    `"Houston, we have a {N1}." - Apollo 13 (1995)`,
    `"Carpe diem. Seize the day, boys. Make your lives {A1}." - Dead Poets Society (1989)`,
    `"Nobody puts Baby in a {N1}." - Dirty Dancing (1987)`,
    `"I'll get you, my {A1}, and your little {N1}, too!" - The Wizard of Oz (1939)`,
    `"As God is my witness, I'll never be {A1} again." - Gone With The Wind (1940)`,
    `"There's no {N1} in baseball!" - A League Of Their Own (1992)`,
    `"A boy's best friend is his {N1}." - Psycho (1960)`,
    `"You've got to ask yourself one question: 'Do I feel {A1}?' Well, do ya, punk?" - Dirty Harry (1971)`,
    `"Greed, for a lack of a better word, is {A1}." - Wall Street (1987)`,
    `"Keep your friends close, but your {N1} closer." - The Godfather Part II`,
    `"May the {N1} be with you." - Star Wars (1977)`,
    `"Fasten your seatbelts. It's going to be a {A1} night." - All About Eve (1950)`,
    `"{N1}." - Citizen Kane (1941)`,
    "Red Dead {N1}",
    "Resident {A1}",
    "{A1} Hill",
    "The {Legend} of Zelda",
    "Castlevania: {N1} of the Night",
    "Castlevania: Symphony of the {N1}",
    "Super {A1} Bros: Melee",
    "{N1} of Legends",
    "The Twilight {N1}",
    "Breaking {A1}",
    "Buffy the {N1} Slayer",
    "Star Trek: The Next {N1}",
    "Mister Rogers' {N1}",
    "{N1} of Cards",
];

module.exports = {
    STORY_PREFIXES,
    STORY_FOR_SYNONYMS
}
