const REVEAL_HERO = 0;
const REVEAL_BACKSTORY = 1;
const REVEAL_STATS = 2;
const REVEAL_SPECIAL = 3;
const SET_OFF = 4;

const QUEST_NEW = 10;
const QUEST_CHAPTER_START = 11;
const QUEST_CHAPTER_END = 12;
const QUEST_FINALE_START = 13;
const QUEST_FINALE_END = 14;

const REST = 50;

const DYING = 97;
const OBITUARY = 98;
const DEAD = 99;

module.exports = {
    REVEAL_HERO,
    REVEAL_BACKSTORY,
    REVEAL_STATS,
    REVEAL_SPECIAL,
    SET_OFF,
    QUEST_NEW,
    QUEST_CHAPTER_START,
    QUEST_CHAPTER_END,
    QUEST_FINALE_START,
    QUEST_FINALE_END,
    REST,
    DYING,
    OBITUARY,
    DEAD,
}
