const REVEAL_HERO = 0;
const REVEAL_BACKSTORY = 1;
const REVEAL_STATS = 2;
const REVEAL_SPECIAL = 3;
const SET_OFF = 4;

const QUEST_FIND = 10;
const QUEST_NEW = 11;
const QUEST_TRAVEL = 12;

const QUEST_CHAPTER_START = 20;
const QUEST_CHAPTER_PATH_END = 21;

const QUEST_FINALE_START = 70;
const QUEST_FINALE_END = 71;

const REST_START = 80;
const REST_END = 81;

const DYING = 97;
const OBITUARY = 98;
const DEAD = 99;

module.exports = {
    REVEAL_HERO,
    REVEAL_BACKSTORY,
    REVEAL_STATS,
    REVEAL_SPECIAL,
    SET_OFF,
    QUEST_FIND,
    QUEST_NEW,
    QUEST_CHAPTER_START,
    QUEST_CHAPTER_PATH_END,
    QUEST_TRAVEL,
    QUEST_FINALE_START,
    QUEST_FINALE_END,
    REST_START,
    REST_END,
    DYING,
    OBITUARY,
    DEAD,
}
