const BOUQUET = "BOUQUET";
const SMALL_KEY = "SMALL KEY";
const TEDDY_BEAR = "TEDDY BEAR";
const DICE = "DICE";
const WOODEN_SWORD = "WOODEN SWORD";
const WOODEN_SHIELD = "WOODEN SHIELD";
const SADDLE = "SADDLE";
const ODD_GEM = "ODD GEM"; // not used yet

module.exports = {
    WOODEN_SHIELD,
    WOODEN_SWORD,
    BOUQUET,
    SADDLE,
    SMALL_KEY,
    TEDDY_BEAR,
    DICE,
    ODD_GEM,
    STARTER_ITEMS: [WOODEN_SWORD, WOODEN_SHIELD, SADDLE],
};
