const REVEAL_HERO = 0;
const REVEAL_BACKSTORY = 1;
const REVEAL_STATS = 2;
const REVEAL_SPECIAL = 3;
const REVEAL_MOVE = 4;
const SET_OFF = 5;

const QUEST_FIND = 10;
const QUEST_NEW = 11;
const QUEST_TRAVEL = 12;

const QUEST_CHAPTER_START = 20;
const QUEST_CHAPTER_PATH_END = 21;
const QUEST_CHAPTER_CHOICE_END = 22;
const QUEST_CHAPTER_DIRECT_END = 23;
const QUEST_CHAPTER_ENCOUNTER_HERO = 24;
const QUEST_CHAPTER_ENCOUNTER_ENEMY = 25;
const QUEST_CHAPTER_ENCOUNTER_END = 26;

const QUEST_FINALE_START = 70;
const QUEST_FINALE_PATH_END = 71;
const QUEST_FINALE_CHOICE_END = 72;
const QUEST_FINALE_DIRECT_END = 73;
const QUEST_FINALE_ENCOUNTER_HERO = 74;
const QUEST_FINALE_ENCOUNTER_ENEMY = 75;
const QUEST_FINALE_ENCOUNTER_END = 76;

const REST_START = 80;
const REST_END = 81;

const DYING = 97;
const OBITUARY = 98;
const DEAD = 99;

const ERR = 100;

module.exports = {
    REVEAL_HERO,
    REVEAL_BACKSTORY,
    REVEAL_STATS,
    REVEAL_SPECIAL,
    REVEAL_MOVE,
    SET_OFF,
    QUEST_FIND,
    QUEST_NEW,
    QUEST_CHAPTER_START,
    QUEST_CHAPTER_PATH_END,
    QUEST_CHAPTER_CHOICE_END,
    QUEST_CHAPTER_DIRECT_END,
    QUEST_CHAPTER_ENCOUNTER_HERO,
    QUEST_CHAPTER_ENCOUNTER_ENEMY,
    QUEST_CHAPTER_ENCOUNTER_END,
    QUEST_TRAVEL,
    QUEST_FINALE_START,
    QUEST_FINALE_PATH_END,
    QUEST_FINALE_CHOICE_END,
    QUEST_FINALE_DIRECT_END,
    QUEST_FINALE_ENCOUNTER_HERO,
    QUEST_FINALE_ENCOUNTER_ENEMY,
    QUEST_FINALE_ENCOUNTER_END,
    REST_START,
    REST_END,
    DYING,
    OBITUARY,
    DEAD,
    ERR,
}
