const HEAL = "HEAL";
const STRENGTH_ATTACK = "STRENGTH_ATTACK";
const DEXTERITY_ATTACK = "DEXTERITY_ATTACK";
const WISDOM_ATTACK = "WISDOM_ATTACK";
const CHARISMA_ATTACK = "CHARISMA_ATTACK";
const FAIL = "FAIL";

module.exports = {
    HEAL,
    STRENGTH_ATTACK,
    DEXTERITY_ATTACK,
    WISDOM_ATTACK,
    CHARISMA_ATTACK,
    FAIL,
};
