const storyPrefixes = [
    "Sherlock Holmes and the Case of the {A1} {N1}",
    "Star Wars Episode XL: The {A1} {N1}",
    "Harry Potter and the {A1} {N1}",
    "Percy Jackson and the {A1} {N1}",
    "Mission: Impossible - {A1} {N1}",
    "Call of Duty: {A1} {N1}",
    "Indiana Jones and the {N1} of {N2}",
    "Indiana Jones and the Kingdom of the {A1} {N1}",
    "Avengers: {A1} {N1}",
    "The Girl With The {A1} {N1}",
    "A Song of {N1} and {N2}",
    "The Hitchhiker's Guide to the {N1}",
    "To Kill a {N1}",
    "The {A1} Gatsby",
    "The {A1} Heart",
    "War and {N1}",
    "{N1} and Peace",
    "{A1} Fiction",
    "Pan's {N1}",
    "{A1} Encounters of the {A2} Kind",
    "The Lord of the Rings: The Return of the {N1}",
    "The Lord of the Rings: The Fellowship of the {N1}",
    "The Beauty and the {N1}",
    "Die {A1}",
    "12 {A1} Men",
    "{N1}busters",
    "{A1} Frankenstein",
    "Almost {A1}",
    "Monty Python and the {A1} {N1}",
    "Eternal Sunshine of the {A1} Mind",
    "Butch Cassidy and the {A1} Kid",
    "The {A1} Lebowski",
    "Some Like It {A1}",
    "A Clockwork {N1}",
    "American {N1}",
    "The {N1} Bride",
    "The {N1} of Music",
    "It's a {A1} Life",
    "Gone With the {N1}",
    "Indiana Jones: Raiders of the Lost {N1}",
    "The {N1} of Oz",
];

module.exports = {
    storyPrefixes
}