const CULPRIT_CLUE_BASES = [
    `{CLUE1} and {CLUE2} were talking about the price of tea in China at the time of the murder.`,
    `Early in the night, before the murder, {CLUE1} and {CLUE2} were asleep.`,
    `At the time of the murder, {CLUE1} was singing a duet with {CLUE2}.`,
    `{CLUE1} and {CLUE2} were committing unrelated crimes at the time of the murder.`,
    `{CLUE1} and {CLUE2} were together all night.`,
    `{CLUE1} and {CLUE2} were with the crowd at the tie of the murder.`,
    `{CLUE1} and {CLUE2} were cooking a meal.`,
    `Both {CLUE1} and {CLUE2} provided solid alibis.`,
    `There was a sports game on during the murder {CLUE1} and {CLUE2} refused to miss, even for a second.`,
    `{CLUE1} was dancing with {CLUE2} at the time of the murder.`,
    `While they are embarrassed to admit it, {CLUE} accidentally locked themselves in a closet all night.`,
    `You find that {CLUE} had no motive to commit the murder.`,
    `Although they were invited, {CLUE} never showed up to the party.`,
    `Your gut tells you that {CLUE} did not do it.`,
    `You most suspect {CLUE}, and its never the person you most suspect.`,
    `{CLUE} had too much to drink and passed out before the murder occurred.`,
    `{CLUE} is clearly being framed.`,
    `{CLUE1} was taking pictures of {CLUE2} at the moment of the murder.`,
    `{CLUE} was at the party via video call, you do not think they could have committed the murder.`,
    `You learn that [VICTIM] and {CLUE} were quite close and planning a trip together. They had no motive.`,
    `{CLUE} had an ankle bracelet on all night. You can confirm their alibi, they were not near the murder.`,
    `There was a fist fight between {CLUE1} and {CLUE2} at the time of the murder.`,
    `{CLUE1} and {CLUE2} were trying to break a world record at the time of the murder.`,
];

const SCENE_CLUE_BASES = [
    `{CLUE1} and {CLUE2} were empty at the time of the murder.`,
    `{CLUE1} and {CLUE2} were being cleaned by several people at the time of the murder.`,
    `{CLUE1} and {CLUE2} were under surveillance at the time of the murder.`,
    `{CLUE1} and {CLUE2} were full of party-goers at the time of the murder.`,
    `Staff ensured that {CLUE1} and {CLUE2} were locked all night.`,
    `{CLUE} was closed for remodelling. Anyone who entered would have left some trace, as wet paint is everywhere.`,
    `{CLUE} was listed as a possible location for the murder, but such a place does not exist.`,
    `{CLUE} is a holy space not fit for murder.`,
    `Party-goers were playing board games in {CLUE} all  night long.`,
    `Party-goers were playing hide-n-seek in {CLUE} all  night long.`,
    `Party-goers were making art in {CLUE} all  night long.`,
    `Party-goers were making music in {CLUE} all  night long.`,
    `Food was set up in {CLUE} all  night long. It would not have been a suitable place to kill someone.`,
    `{CLUE} was certainly not the scene of the crime.`,
    `You mixed up your notes, [MANOR] does not have a {CLUE}.`,
    `The ghost that haunts {CLUE} tells you that nobody was in here last night.`,
    `{CLUE} has really creaky floors. If anyone had been in there, people would have noticed.`,
    `{CLUE} is dusty and clearly has not been occupied in a long time.`,
    `You don't ask why, but {CLUE} is full of dolls. There is not room for a murder.`,
    `A photo-shoot was happening at {CLUE} at the time of the murder.`,
    `Children were asleep in {CLUE} at the time of the murder. They did not wake up and are light sleepers.`,
    `{CLUE} would have been too obvious a place for a murder. You can rule that out.`,
    `{CLUE} was being guarded by a dog all night.`,
];

const WEAPON_CLUE_BASES = [
    `While they could have been deadly, {CLUE1} and {CLUE2} were locked away at the time of the murder.`,
    `{CLUE1} and {CLUE2} were being used by party-goers at the time of the murder. You don't want to ask how.`,
    `{CLUE1} and {CLUE2} were on display at the time of the murder.`,
    `{CLUE1} and {CLUE2} were being used by staff at the time of the murder.`,
    `{CLUE1} and {CLUE2} are both covered in glitter. If they were used, it would be obvious.`,
    `Your colleague investigates {CLUE1} and {CLUE2}. Neither could have been used.`,
    `Your own investigation suggests that {CLUE1} and {CLUE2} could not have been used.`,
    `{CLUE1} and {CLUE2} look dangerous at first, but could not have been used.`,
    `{CLUE} was in plain sight all night long. Nobody could have taken it.`,
    `{CLUE} was extremely smelly. You aren't sure why. If anyone touched it, they would smell.`,
    `{CLUE} was not involved with the murder. Multiple party-goers confirm this.`,
    `{CLUE}? There's no way that could have been used.`,
    `{CLUE} catches your eye. You send it to the lab and find that it was definitely not used for murder.`,
    `{CLUE} is too heavy to have been moved by one person.`,
    `{CLUE} is extremely fragile, there's no way it could have been used.`,
    `{CLUE} was being used for a game all night long.`,
    `{CLUE} was brought to the party after the murder happened.`,
    `{CLUE} is covered in fingerprints, but none of them match any suspects.`,
    `There's no way that {CLUE} could have been used to kill someone.`,
    `The cause of death does not fit murder by {CLUE}.`,
    `{CLUE} is an antique and would be broken if it had been used.`,
    `{CLUE} is an art piece and an alarm would have gone off if someone touched it.`,
    `The dog was playing with {CLUE} all night.`,
    `You find no fingerprints on {CLUE}.`,
    `You investigate {CLUE} and realize it is simply a prop and could not have been used to commit murder.`,
];

module.exports = {
    SCENE_CLUE_BASES,
    WEAPON_CLUE_BASES,
    CULPRIT_CLUE_BASES
}
