const CULPRITS = [
    "Mr. Teal",
    "Doctor Chartreuse",
    "Chef Ratatouille",
    "Professor Chalmers",
    "Elizabeth Bloodwell",
    "Hamilton Alexandre",
    "Ms. Terri",
    "Old MacDonald",
    "De Tektiv",
    "Captain O' Ship",
    "Fido",
    "John Smith",
    "Jane Doe",
    "The Count",
    "Sergeant Ketchup",
    "Granny",
    "Miss Scarlet",
    "Yvette",
    "Mrs. Peacock",
    "Colonel Mustard",
    "Professor Plum",
    "Mr. Green",
    "Mr. Boddy",
    "Mrs. White",
    "The Singing Telegram Girl",
    "Wadsworth",
    "The Cook",
    "Sherlock Holmes",
    "Miss Peach",
    "Monsieur Brunette",
    "Madame Rose",
    "Sergeant Gray",
    "Dr. Orchid",
    "The Thief",
    "Mr. Slate-Grey",
    "Captain Brown",
    "Lady Lavender",
    "Mr. Meadow-Brook",
    "Mrs. Meadow-Brook",
    "Prince Azure",
    "Rusty Nayler",
    "Lord Gray",
    "Hogarth",
    "The Black Dog",
    "Editor Braunman",
    "The Reporter",
    "Inspector Brown",
    "The Butler",
    "A Mysterious Stranger",
    "The Judge",
    "The Reverend",
    "Nancy Drew",
    "Veronica Mars",
    "Fred",
    "Daphne",
    "Velma",
    "Scooby-Doo",
    "Shaggy",
    "Batman",
    "Inspector Clouseau",
    "Inspector Lestrade",
    "Dirk Gently",
    "Gus",
    "Mulder",
    "Scully",
    "Irene Adler",
    "Professor Moriarty",
    "Columbo",
    "Dupin",
    "Professor Layton",
    "Kyoko Kirigiri",
    "Shuichi Saihara",
    "Tommy Beresford",
    "Phoenix Wright",
    "Miles Edgeworth",
    "Laura Palmer",
    "Dale Cooper",
    "Audrey Horne",
    "Shelly Johnson",
    "Log Lady",
    "Monk",
    "Scrappy Doo",
    "Dr. Jekyll",
    "Luke Triton",
    "Flora Reinhold",
    "Don Paolo",
    "Godot",
    "Kermit",
    "Hannibal",
    "The Oracle",
    "Patrick Bateman",
    "Dr. Watson",
    "Hannibal Lecter",
    "Jane Eyre",
    "Paddington Brown",
    "Detective Pikachu",
    "Inspector Gadget",
    "Dr. Claw",
    "Agent 99",
    "Maxwell Smart",
];

module.exports = {
    CULPRITS
}
