const SCENES = [
    "The Pool",
    "The Observatory",
    "The Kitchen",
    "The Art Studio",
    "The Wine Cellar",
    "The Bathroom",
    "The Backyard",
    "The Garage",
    "The Study",
    "The Dining Room",
    "The Master Bedroom",
    "The Guest Bedroom",
    "The Theatre",
    "The Panic Room",
    "The Library",
    "The Green House",
    "The Billiard Room",
    "The Lounge",
    "The Ballroom",
    "The Sitting Room",
    "The Foyer",
    "The Sauna",
    "The Junk Room",
    "The Workshop",
    "The Crawlspace",
    "The Bowling Alley",
    "The Music Room",
    "The Sanctuary",
    "The Attic",
    "The Loft",
    "The Balcony",
    "The Living Room",
    "The Nursery",
    "The Mud Room",
    "The Games Room",
    "The Walk-In Closet",
    "The Porch",
    "The Shed",
    "The Tree House",
    "The Utility Room",
    "The Spare Room",
    "The Server Room",
    "The Prayer Room",
    "The Bar",
    "The Dojo",
    "The Vault",
    "The Locker Room",
    "The Roof",
    "The Secret Passageway",
    "The Flower Garden",
    "The Docks",
    "The Poker Room",
    "The Pantry",
    "The Control Room",
    "The Entryway",
    "The Cheese Cabinet",
    "The Generator Room",
    "The Furnace Room",
    "The Surveillance Room",
    "The Art Gallery",
    "The Model Train Room",
    "The Distillery",
    "The Computer Room",
    "The Office",
    "The Fire Escape",
    "The Boudoir",
    "The Rotunda",
    "The Powder Room",
    "The Cloak Room",
    "The Cabana",
    "The Dance Studio",
    "The Zen Garden",
    "The Stables",
    "The Spiral Staircase",
    "The Driveway",
    "The Dumbwaiter",
    "The Dumpster",
    "The Climbing Room",
    "The Gear Room",
    "The Jacuzzi",
    "The Fencing Room",
    "The Archery Range",
    "The Shooting Gallery",
    "The Tutor's Room",
    "The Nanny's Room",
    "The Butler's Room",
    "The Cook's Room",
    "The Sewing Room",
    "The Fitting Room",
    "The Parlor",
    "The Drawing Room",
    "The Tennis Court",
    "The Pool House",
    "The Guest House",
    "The Receiving Room",
    "The Throne Room",
    "The Gym",
    "The Yoga Studio",
    "The Snack Bar",
    "The Green Room",
];

module.exports = {
    SCENES
}
