const SCENES = [
    "The Pool",
    "The Observatory",
    "The Kitchen",
    "The Art Studio",
    "The Wine Cellar",
    "The Bathroom",
    "The Backyard",
    "The Garage",
    "The Study",
    "The Dining Room",
    "The Master Bedroom",
    "The Guest Bedroom",
    "The Theatre",
    "The Panic Room",
    "The Library",
    "The Green House",
    "The Billiard Room",
    "The Lounge",
    "The Ballroom",
    "The Sitting Room",
    "The Foyer",
    "The Sauna",
    "The Junk Room",
    "The Workshop",
    "The Crawlspace",
    "The Bowling Alley",
    "The Music Room",
    "The Sanctuary",
    "The Attic",
    "The Loft",
    "The Balcony",
    "The Living Room",
    "The Nursery",
    "The Mud Room",
    "The Games Room",
    "The Walk-In Closet",
    "The Porch",
    "The Shed",
    "The Tree House",
    "The Utility Room",
    "The Spare Room",
    "The Server Room",
    "The Prayer Room",
    "The Bar",
    "The Dojo",
    "The Vault",
    "The Locker Room",
    "The Roof",
    "The Secret Passageway",
];

module.exports = {
    SCENES
}
